bq_dbt:
  outputs:
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      fixed_retries: 1
      keyfile: /root/.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
